### ISSUE TITLE
draft plans for coordination, documentation, and communications

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop-client#1304]
### Coordination with Localization Lab

1. [x] @cfm shadows @conorsch as deputy localization manager for [SecureDrop 2.1.0](https://github.com/freedomofpress/securedrop/issues/6103)
2. [x] Introductory meeting with Localization Lab (October 20)
3. [ ] Update Localization Lab

### Documentation

https://github.com/freedomofpress/securedrop-client/wiki/Internationalization

[Divio documentation](https://documentation.divio.com/#about-the-system) matrix:

| | Study | Work |
| --- | --- | --- |
| **Practical** | [x] [tutorial](https://github.com/freedomofpress/securedrop-client/wiki/Internationalization#tutorial) | [ ] how-to guide |
| **Theoretical** | [ ] explanation | [x] [reference](https://github.com/freedomofpress/securedrop-client/wiki/Internationalization#overview) |

1. [x] *Adapt* SecureDrop Server's ["Internationalization"](https://docs.securedrop.org/en/stable/development/i18n.html) page for #1348
    - ~...in `securedrop-client`'s readme?~
    - ~...in a separate Markdown file?~
    - **...in the `securedrop-client` wiki?**  →  https://github.com/freedomofpress/securedrop-client/wiki/Internationalization
    - ~...elsewhere?~
2. [x] *Update* SecureDrop Server's ["Translations"](https://docs.securedrop.org/en/stable/development/translations.html) page in place, in particular:  freedomofpress/securedrop-docs#289
    - [x] https://docs.securedrop.org/en/stable/development/translations.html?highlight=translation#how-to-change-an-existing-translation
    - [x] https://docs.securedrop.org/en/stable/development/translations.html?highlight=translation#how-to-use-the-language-glossaries-on-weblate
    - [x] https://docs.securedrop.org/en/stable/development/translations.html?highlight=translation#how-to-use-securedrop-s-demo-server
3. [x] *Document* the differences between the two workflows (à la #1348), such as where/when:
    1. [x] the template translation catalog (`.pot`) is generated
    2. [x] individual translation catalogs (`.po`) are updated
    3. [x] machine objects (`.mo`) are compiled in development versus for production artifacts.  We differ from `securedrop`'s model:
        - SecureDrop production: https://github.com/freedomofpress/securedrop/blob/5584c8dd458c82901e2542e172a82827f6ee3c36/install_files/ansible-base/roles/build-securedrop-app-code-deb-pkg/tasks/translations.yml#L29-L34
        - SecureDrop development: https://github.com/freedomofpress/securedrop/blob/717dc6983e2475086f30aa016bcde496aa8bfefd/securedrop/bin/dev-deps#L112-L113

### Communications

[Drafts](https://docs.google.com/document/d/1Rh5muL-O_w-retXyWB1oLosPVhUEdfCj5yuSGl6rImE/edit#) for:

1. Pinned threads in ["Translations"](https://forum.securedrop.org/c/translations/5) Discourse category
2. Announcement and/or blog post
3. https://community.internetfreedomfestival.org/community/channels/localization-lab-chat

## Open questions

1. [x] What are translators expected to (have to) do to see strings in context?  → 
 https://github.com/freedomofpress/securedrop-client/issues/1304#issuecomment-1024588003
    - Translator comments
    - Run SecureDrop Client themselves?
    - Look at screenshots?—generated where?
2. [x] How is localization tested?  →  #1398
3. [x] With continuous localization, will there be a Localization Manager continuously available?  →  to be discussed during orientation session

**Comment by cfm** [comment]
@creviera, today @eloquence and I discussed this rough plan for rolling out translation of the SecureDrop Client.  The timeline would be TBD after the SecureDrop 2.1.0, but my hunch is that we can move this forward incrementally throughout October.

Feedback welcome on any of it!  In particular, @eloquence recommended the `securedrop-client` wiki as the best place for documenting this workflow for translators (in comparison to SecureDrop Server's ["Internationalization"](https://docs.securedrop.org/en/stable/development/i18n.html) page).  Let me know if you think there's a better venue.

**Comment by cfm** [comment]
After #1317, this proposal will need to be updated based on our meeting today with @Localization-Lab.

**Comment by cfm** [comment]
Because <https://workstation.securedrop.org/> is still strictly user-facing, I've opted to start *drafting* (at least) this documentation in <https://github.com/freedomofpress/securedrop-client/wiki/Internationalization>.  We can revisit this if this material outgrows a single wiki page, needs Sphinx and ReST rather than Markdown, warrants pull-request review, &c.  :-)

**Comment by cfm** [comment]
A first draft of the developer- and maintainer-facing documentation is available at <https://github.com/freedomofpress/securedrop-client/wiki/Internationalization>.  Feedback welcome!

Changes to the existing translator-facing documentation for SecureDrop are outlined above.

On the latter, here's a conclusion on which I'd appreciate a reality check:  Pending #1004 and freedomofpress/securedrop-workstation#524, it seems that we're not going to be able to give SecureDrop Client translators access to an automatically-generated set of screenshots, never mind an interactive demo.  We'll have to see whether the screenshots included in the [Workstation documentation](https://workstation.securedrop.org/en/stable/index.html) give translators sufficient context.

**Comment by cfm** [comment]
<https://github.com/freedomofpress/securedrop-client/issues/1304#issuecomment-1017054113>:

> Pending #1004 and freedomofpress/securedrop-workstation#524, it seems that we're not going to be able to give SecureDrop Client translators access to an automatically-generated set of screenshots, never mind an interactive demo. We'll have to see whether the screenshots included in the Workstation documentation give translators sufficient context.

In freedomofpress/securedrop-docs#289, I've proposed this as the official recommendation for how translators of the SecureDrop Client should familiarize themselves with the context of source strings presented in Weblate.

**Comment by cfm** [comment]
As of freedomofpress/securedrop-docs#289 and [these draft communications](https://docs.google.com/document/d/1Rh5muL-O_w-retXyWB1oLosPVhUEdfCj5yuSGl6rImE/edit#), this ticket is substantively complete.  Next steps are:

1. the SecureDrop team's internal orientation session on SecureDrop Server/Client localization;
2. to update Localization Lab on these plans; and
3. to finalize the communications drafted here.
