### ISSUE TITLE
rework localization Make targets for PR-level use

### ISSUE THREAD

**Issue by cfm** [freedomofpress/securedrop-client#1317]
## Context

In #1282 we implemented:

1. a Make target `update-translation-catalogs` to extract source strings from `securedrop_client/**/*.py` for Weblate to make available to translators; and
2. a GitHub Actions workflow `l10n` to make this target nightly on `main`.

[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcblxuZGV2ZWxvcGVyc1tEZXZlbG9wZXJzXVxuV2VibGF0ZSgoV2VibGF0ZSkpXG50cmFuc2xhdG9yc1t0cmFuc2xhdG9yc11cblxuZGV2ZWxvcGVycyAtLTEuIFB1c2gtLT4gbWFpblxubWFpbiAtLlwiMi4gW0RhaWx5XSBVcGRhdGluZzxicj4oZXh0cmFjdGluZyttZXJnaW5nKTxicj50cmFuc2xhdGlvbiBjYXRhbG9nc1wiLi0-IG1haW5cbm1haW4gLS1cIjMuIFB1bGwgKHRyaWdnZXJlZCBieSB3ZWIgaG9vaylcIi0tPiBXZWJsYXRlXG5XZWJsYXRlIC0tNC4gTm90aWZpY2F0aW9uLS0-IHRyYW5zbGF0b3JzXG50cmFuc2xhdG9ycyAtLTUuIFRyYW5zbGF0ZS0tPiBXZWJsYXRlXG5XZWJsYXRlIC0tXCI2LiBQdXNoPGJyPihpbmNsdWRpbmcgdXBzdHJlYW08YnI-Y29tbWl0cyBmcm9tIHN0ZXAgMylcIi0tPiBXZWJsYXRlTWFpblxuV2VibGF0ZU1haW4gLS03LiBQUiAtLT4gbWFpblxuXG5zdWJncmFwaCBHaXRIdWJcbnN1YmdyYXBoIGZyZWVkb21vZnByZXNzL3NlY3VyZWRyb3AtY2xpZW50XG5tYWluW1wibWFpblwiXVxuZW5kXG5cbnN1YmdyYXBoIHdlYmxhdGUtZnBmL3NlY3VyZWRyb3AtY2xpZW50XG5XZWJsYXRlTWFpblt3ZWJsYXRlLXNlY3VyZWRyb3Atc2VjdXJlZHJvcC1jbGllbnRdXG5lbmRcblxuZW5kXG4iLCJtZXJtYWlkIjp7InRoZW1lIjoiZGVmYXVsdCJ9LCJ1cGRhdGVFZGl0b3IiOmZhbHNlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6ZmFsc2V9)](https://mermaid-js.github.io/mermaid-live-editor/edit/##eyJjb2RlIjoiZ3JhcGggVERcblxuZGV2ZWxvcGVyc1tEZXZlbG9wZXJzXVxuV2VibGF0ZSgoV2VibGF0ZSkpXG50cmFuc2xhdG9yc1t0cmFuc2xhdG9yc11cblxuZGV2ZWxvcGVycyAtLTEuIFB1c2gtLT4gbWFpblxubWFpbiAtLlwiMi4gW0RhaWx5XSBVcGRhdGluZzxicj4oZXh0cmFjdGluZyttZXJnaW5nKTxicj50cmFuc2xhdGlvbiBjYXRhbG9nc1wiLi0-IG1haW5cbm1haW4gLS1cIjMuIFB1bGwgKHRyaWdnZXJlZCBieSB3ZWIgaG9vaylcIi0tPiBXZWJsYXRlXG5XZWJsYXRlIC0tNC4gTm90aWZpY2F0aW9uLS0-IHRyYW5zbGF0b3JzXG50cmFuc2xhdG9ycyAtLTUuIFRyYW5zbGF0ZS0tPiBXZWJsYXRlXG5XZWJsYXRlIC0tXCI2LiBQdXNoPGJyPihpbmNsdWRpbmcgdXBzdHJlYW08YnJjb21taXRzIGZyb20gc3RlcCAzKVwiLS0-IFdlYmxhdGVNYWluXG5XZWJsYXRlTWFpbiAtLTcuIFBSIC0tPiBtYWluXG5cbnN1YmdyYXBoIEdpdEh1Ylxuc3ViZ3JhcGggZnJlZWRvbW9mcHJlc3Mvc2VjdXJlZHJvcC1jbGllbnRcbm1haW5bXCJtYWluXCJdXG5lbmRcblxuc3ViZ3JhcGggd2VibGF0ZS1mcGYvc2VjdXJlZHJvcC1jbGllbnRcbldlYmxhdGVNYWluW3dlYmxhdGUtc2VjdXJlZHJvcC1zZWN1cmVkcm9wLWNsaWVudF1cbmVuZFxuXG5lbmRcbiIsIm1lcm1haWQiOiJ7XG4gIFwidGhlbWVcIjogXCJkZWZhdWx0XCJcbn0iLCJ1cGRhdGVFZGl0b3IiOmZhbHNlLCJhdXRvU3luYyI6dHJ1ZSwidXBkYXRlRGlhZ3JhbSI6ZmFsc2V9)

In freedomofpress/infrastructure#3593 we have since concluded that this workflow requires that our @weblate-fpf bot push directly to `main`, which we are not willing to allow.

## Goal

After discussing a number of [alternatives](https://docs.google.com/presentation/d/1A3XVczgCg-3wUS9EjUSbeb3ea0YWioQ-w7YflwQRcIE/edit), we have decided to adapt #1282's Make targets to be used interactively by developers (and perhaps in a Git pre-commit hook) and then enforced linter-style in CI.

[![](https://mermaid.ink/img/eyJjb2RlIjoiZ3JhcGggVERcblxuc3ViZ3JhcGggbG9jYWxseVxuZGV2ZWxvcGVyc1tEZXZlbG9wZXJzXVxubWFrZS11cGRhdGVbXCJtYWtlIHVwZGF0ZS10cmFuc2xhdGlvbi1jYXRhbG9nczxicj4ob3IgdmlhIGAuZ2l0L2hvb2tzL3ByZS1jb21taXRgKVwiXVxuZW5kXG5cbnN1YmdyYXBoIENpcmNsZUNJXG5tYWtlLWNoZWNrW1wibWFrZSBjaGVjay10cmFuc2xhdGlvbi1jYXRhbG9nc1wiXVxuZW5kXG5cbldlYmxhdGUoKFdlYmxhdGUpKVxudHJhbnNsYXRvcnNbdHJhbnNsYXRvcnNdXG5cbmRldmVsb3BlcnMgLS1cIjEuXCItLT4gbWFrZS11cGRhdGVcbmRldmVsb3BlcnMgLS0yLiBQdXNoLS0-IFBSXG5QUiAtLlwiMy5cIi4tPiBtYWtlLWNoZWNrXG5tYWtlLWNoZWNrIC0tXCIzLiBpZiAkPyA9PSAwXCItLT4gUFJcblBSIC0uXCI0LiBvbmNlIG1haW50YWluZXIgYXBwcm92ZXNcIi4tPiBtYWluXG5tYWluIC0tXCI1LiBQdWxsICh0cmlnZ2VyZWQgYnkgd2ViIGhvb2spXCItLT4gV2VibGF0ZVxuV2VibGF0ZSAtLTYuIE5vdGlmaWNhdGlvbi0tPiB0cmFuc2xhdG9yc1xudHJhbnNsYXRvcnMgLS03LiBUcmFuc2xhdGUtLT4gV2VibGF0ZVxuV2VibGF0ZSAtLVwiOC4gUHVzaDxicj4oaW5jbHVkaW5nIHVwc3RyZWFtPGJyPmNvbW1pdHMgZnJvbSBzdGVwIDUpXCItLT4gV2VibGF0ZU1haW5cbldlYmxhdGVNYWluIC0tOS4gUFIgLS0-IG1haW5cblxuc3ViZ3JhcGggR2l0SHViXG5zdWJncmFwaCBmcmVlZG9tb2ZwcmVzcy9zZWN1cmVkcm9wLWNsaWVudFxubWFpbltcIm1haW5cIl1cblBSPlBSXVxuZW5kXG5cbnN1YmdyYXBoIHdlYmxhdGUtZnBmL3NlY3VyZWRyb3AtY2xpZW50XG5XZWJsYXRlTWFpblt3ZWJsYXRlLXNlY3VyZWRyb3Atc2VjdXJlZHJvcC1jbGllbnRdXG5lbmRcblxuZW5kIiwibWVybWFpZCI6eyJ0aGVtZSI6ImRlZmF1bHQifSwidXBkYXRlRWRpdG9yIjpmYWxzZSwiYXV0b1N5bmMiOnRydWUsInVwZGF0ZURpYWdyYW0iOmZhbHNlfQ)](https://mermaid-js.github.io/mermaid-live-editor/edit/#eyJjb2RlIjoiZ3JhcGggVERcblxuc3ViZ3JhcGggbG9jYWxseVxuZGV2ZWxvcGVyc1tEZXZlbG9wZXJzXVxubWFrZS11cGRhdGVbXCJtYWtlIHVwZGF0ZS10cmFuc2xhdGlvbi1jYXRhbG9nczxicj4ob3IgdmlhIGAuZ2l0L2hvb2tzL3ByZS1jb21taXRgKVwiXVxuZW5kXG5cbnN1YmdyYXBoIENpcmNsZUNJXG5tYWtlLWNoZWNrW1wibWFrZSBjaGVjay10cmFuc2xhdGlvbi1jYXRhbG9nc1wiXVxuZW5kXG5cbldlYmxhdGUoKFdlYmxhdGUpKVxudHJhbnNsYXRvcnNbdHJhbnNsYXRvcnNdXG5cbmRldmVsb3BlcnMgLS1cIjEuXCItLT4gbWFrZS11cGRhdGVcbmRldmVsb3BlcnMgLS0yLiBQdXNoLS0-IFBSXG5QUiAtLlwiMy5cIi4tPiBtYWtlLWNoZWNrXG5tYWtlLWNoZWNrIC0tXCIzLiBpZiAkPyA9PSAwXCItLT4gUFJcblBSIC0uXCI0LiBvbmNlIG1haW50YWluZXIgYXBwcm92ZXNcIi4tPiBtYWluXG5tYWluIC0tXCI1LiBQdWxsICh0cmlnZ2VyZWQgYnkgd2ViIGhvb2spXCItLT4gV2VibGF0ZVxuV2VibGF0ZSAtLTYuIE5vdGlmaWNhdGlvbi0tPiB0cmFuc2xhdG9yc1xudHJhbnNsYXRvcnMgLS03LiBUcmFuc2xhdGUtLT4gV2VibGF0ZVxuV2VibGF0ZSAtLVwiOC4gUHVzaDxicj4oaW5jbHVkaW5nIHVwc3RyZWFtPGJyPmNvbW1pdHMgZnJvbSBzdGVwIDUpXCItLT4gV2VibGF0ZU1haW5cbldlYmxhdGVNYWluIC0tOS4gUFIgLS0-IG1haW5cblxuc3ViZ3JhcGggR2l0SHViXG5zdWJncmFwaCBmcmVlZG9tb2ZwcmVzcy9zZWN1cmVkcm9wLWNsaWVudFxubWFpbltcIm1haW5cIl1cblBSPlBSXVxuZW5kXG5cbnN1YmdyYXBoIHdlYmxhdGUtZnBmL3NlY3VyZWRyb3AtY2xpZW50XG5XZWJsYXRlTWFpblt3ZWJsYXRlLXNlY3VyZWRyb3Atc2VjdXJlZHJvcC1jbGllbnRdXG5lbmRcblxuZW5kIiwibWVybWFpZCI6IntcbiAgXCJ0aGVtZVwiOiBcImRlZmF1bHRcIlxufSIsInVwZGF0ZUVkaXRvciI6ZmFsc2UsImF1dG9TeW5jIjp0cnVlLCJ1cGRhdGVEaWFncmFtIjpmYWxzZX0)

In addition to removing the requirement that @weblate-fpf be able to push directly to `main`, this approach has two new advantages:

1. Changes in the message catalog (`securedrop_client/locale/messages.pot`) will be recorded in the same commit, and reviewed in the same pull request, as the changes in the source strings from which they are extracted.
2. Contributors and reviewers will have commit- and merge-time responsibility, respectively, for the quality of the source strings that get pushed to Weblate for translators to work with.  (Thanks to the @Localization-Lab team for highlighting this consideration.)

## Steps

1. [x] Remove the `l10n` GitHub Actions workflow.
2. [x] Define a new Make target `check-translation-catalogs`, which returns `0` iff `make update-translation-catalogs` is a no-op (i.e., `git diff --quiet || exit 1` with a helpful warning).
    - [x] Revert b1e8e0be10d430f96ce3754e5b76b03b5bdb4958
3. [x] Add `make check-translation-catalogs` to the `lint` CircleCI job, making it a requirement for a pull request to pass CI.
4. [x] Investigate whether any of #1282's other Make targets can be obviated by using [Weblate add-ons](https://docs.weblate.org/en/weblate-4.6.2/admin/addons.html#built-in-addons).
    - [ ] Update #1294 and #239 accordingly.
5. [x] Add a Git pre-commit hook for `make {check,update}-translation-catalogs`.
6. [x] Remove unnecessary Make targets (after step 4) and make sure remaining targets are documented in `make help`.

**Comment by cfm** [comment]
@creviera and I met today to discuss proposals #1347 and #1348 and their [background considerations](https://gist.github.com/cfm/d3173206f55d7e44152928fcfd215031).  We affirmed our interest in these proposals over the previous #1282, because they:

1. move source-string changes entirely into the commits that contain their originating code changes; and thereby
2. make them, along with their accompany translation burden, visible to maintainers when they review pull requests.

Between the two options, we favor #1348, which:

1. extracts string changes `.py` → `.pot` via `make update-strings`, enforced via CI `make check-strings`;
2. merges `.pot` → `.po` via Weblate, prior to making `.po` catalogs available for translators to work on; and
3. compiles `.po` → `.mo` via Weblate, as part of the pull request to merge new translations into `main`.

Compared to #1347, (2) lets us minimize the noisiness of diffs in pull requests and eliminate some custom tooling.  Compared to both #1347 and #1282, (3) lets us eliminate some custom tooling and its dependencies in `securedrop-debian-packaging`.

My next steps:

1. [ ] Close #1347 
2. [ ] Commit (or at least document) the removals suggested above
3. [ ] Mark #1348 ready for @creviera's review
