### ISSUE TITLE
Release SecureDrop Client 0.12.0

### ISSUE THREAD

**Issue by rocodes** [freedomofpress/securedrop-client#2126]
This issue tracks the SecureDrop Client release 0.12.0. It will be organized by:

- Release Manager: I guess me :) 
- Deputy Release Manager: @legoktm  (?)
- Comms: @rocodes 

This release includes the following changes:
- bugfix: #2119 
- UI improvements : #1926, https://github.com/freedomofpress/securedrop-client/issues/2098, https://github.com/freedomofpress/securedrop-client/issues/2125
- additional filetype support: https://github.com/freedomofpress/securedrop-client/issues/2110
- updated dependencies: https://github.com/freedomofpress/securedrop-client/pull/2134

SecureDrop maintainers and testers: As you QA this release, please report back your testing results as comments on this ticket. File GitHub issues for any problems found, tag them "QA: Release", and associate them with the release milestone for tracking (or ask a maintainer to do so).

### Fresh install testing
**Setup**
- [ ] Qubes 4.2.2
- [ ] Install prod RPM
- [ ] Before running `apply`:
- [ ] Make a copy of `/srv/salt/securedrop_salt/apt_freedom_press.sources.j2`, `/srv/salt/securedrop_salt/apt_qa_freedom_press.sources.j2` in which you change the apt repo to https://apt-qa.freedom.press
- [ ] Edit `/srv/salt/securedrop_salt/sd-default-config.yml` to point to the apt-qa sources file
- [ ] Run `apply`

**Testing**
- [ ] Provisioning completes successfully
- [ ] See shared test path

### Upgrade Testing
**Setup**
- [ ] prod installation (Qubes 4.2.2, SDW prod)
- [ ] Edit `/etc/apt/sources.list/securedrop_workstation.list` in both the small and the large templates so that they point to `apt-qa.securedrop.org`, then shut down the templates and vms.
- [ ] Run the updater.

**Upgrade Testing**
- [ ] Updater run completes successfully
- [ ] See shared test path

### Test plan
**All install scenarios**
- [ ] All securedrop debian packages are on 0.12.0 (`dpkg -l | grep securedrop` in each template)
- [ ] `.heic`, `.avif` viewing support: These images can be viewed in sd-viewer (#2110)
- [ ] Can print documents of various supported types (`.jpeg`, `.docx`, `.pdf`, `.rtf`) (#2119)
- [ ] ... and during the time between clicking Print and the xpp panel popping up (eg during conversion to PDF for non PDF types), the Continue button is grayed out and shows an animated spinner (#2125)
- [ ] Printing dialog now shows hover and click colours (#2125)
- [ ] Exporting to VM is successful, and repeatedly clicking the "Continue" button has no ill effects on the export flow (#1926)
- [ ] General testing functionality: one tester to follow basic acceptance testing (sync, reply, download, delete source, etc). Please inspect error logs in `sd-app` and the journal in `dom0` and note anything unexpected
- [ ] Pseudolocale (`LANG=en_XA`) QA per <https://github.com/freedomofpress/securedrop-workstation/wiki/Workstation-Acceptance-Tests#internationalization-reference>

## Release tasks

- [ ] Check if there are any security bug fixes waiting to be pulled into the RC
- [ ] Check if there are any translations:
    - [ ] pending merge into `main`
    - [ ] pending inclusion as a supported language in [`MANIFEST.in`](https://github.com/freedomofpress/securedrop-client/blob/main/MANIFEST.in)
- [ ] Update changelog
- [ ] Create test plan
- [ ] Refresh nightlies
- [ ] Begin formal QA using nightlies; refresh nightlies as needed
- [ ] Build production package in standard [build environment](https://github.com/freedomofpress/securedrop-builder/wiki/FAQ#how-do-i-create-a-local-environment-suitable-for-building-packages)
- [ ] Sign production package
- [ ] Perform final pre-flight testing using apt-qa.freedom.press
  - [ ] **Localization:** In a dispVM, change your locale (e.g.: `export LANG=es_ES.utf-8; dpkg-reconfigure locales`), run the Client, and confirm that the application is translated.
- [ ] Publish production package
- [ ] Publicize release via support channels

**Comment by rocodes** [comment]
SecureDrop Client 0.12.0 packages are now available on apt-qa.freedom.press. Testers, please indicate whether you followed the upgrade or clean install plan :)

**Comment by rocodes** [comment]
### Upgrade Testing
**Setup**
- [x] prod installation (Qubes 4.2.2, SDW prod)
- [x] Edit `/etc/apt/sources.list/securedrop_workstation.list` in both the small and the large templates so that they point to `apt-qa.securedrop.org`, then shut down the templates and vms.
- [x] Run the updater.

**Upgrade Testing**
- [x] Updater run completes successfully

### Test plan
**All install scenarios**
- [x] All securedrop debian packages are on 0.12.0 (`dpkg -l | grep securedrop` in each template)
- [x] `.heic`, `.avif` viewing support: These images can be viewed in sd-viewer (#2110)
- [x] Can print documents of various supported types (`.jpeg`, `.docx`, `.pdf`, `.rtf`) (#2119)
- [x] ... and during the time between clicking Print and the xpp panel popping up (eg during conversion to PDF for non PDF types), the Continue button is grayed out and shows an animated spinner (#2125)
- [x] Printing dialog now shows hover and click colours (#2125)
- [x] Exporting to VM is successful, and repeatedly clicking the "Continue" button has no ill effects on the export flow (#1926)

- [ ] General testing functionality: one tester to follow basic acceptance testing (sync, reply, download, delete source, etc). Please inspect error logs in `sd-app` and the journal in `dom0` and note anything unexpected
- [ ] Pseudolocale (`LANG=en_XA`) QA per <https://github.com/freedomofpress/securedrop-workstation/wiki/Workstation-Acceptance-Tests#internationalization-reference>
(TK)

**Comment by legoktm** [comment]
_testing printing now_

Hardware: T490

### Fresh install testing
**Setup**
- [x] Qubes 4.2.2
- [x] Install prod RPM
- [x] Before running `apply`:
- [x] Make a copy of `/srv/salt/securedrop_salt/apt_freedom_press.sources.j2`, `/srv/salt/securedrop_salt/apt_qa_freedom_press.sources.j2` in which you change the apt repo to https://apt-qa.freedom.press
- [x] Edit `/srv/salt/securedrop_salt/sd-default-config.yml` to point to the apt-qa sources file
- [x] Clear salt cache with `sudo rm -rf /var/salt/cache && sudo qubesctl saltutil.sync_all`
- [x] Run `apply`

**Testing**
- [x] Provisioning completes successfully

### Test plan
**All install scenarios**
- [x] All securedrop debian packages are on 0.12.0 (`dpkg -l | grep securedrop` in each template)
- [x] `.heic`, `.avif` viewing support: These images can be viewed in sd-viewer (#2110)
- [ ] Can print documents of various supported types (`.jpeg`, `.docx`, `.pdf`, `.rtf`) (#2119)
- [ ] ... and during the time between clicking Print and the xpp panel popping up (eg during conversion to PDF for non PDF types), the Continue button is grayed out and shows an animated spinner (#2125)
- [ ] Printing dialog now shows hover and click colours (#2125)
- [x] Exporting to VM is successful, and repeatedly clicking the "Continue" button has no ill effects on the export flow (#1926)
- [x] General testing functionality: one tester to follow basic acceptance testing (sync, reply, download, delete source, etc). Please inspect error logs in `sd-app` and the journal in `dom0` and note anything unexpected
- [ ] Pseudolocale (`LANG=en_XA`) QA per <https://github.com/freedomofpress/securedrop-workstation/wiki/Workstation-Acceptance-Tests#internationalization-reference>

**Comment by rocodes** [comment]
Hey @deeplow thank you for your thorough QA as always :)

Sadly, printing heic files is not supported : #918 is an open issue, but the good news is I have already been working on some changes that will a) stop trying to print unprintable files and show an error to the user and b) broaden the types of files we can print. I want to propose these changes for a soon milestone, either 0.13.0 or 0.14.0. 

The delay you saw in the spinner is maybe a resource constraint on your app vm? The pyqt signal is sent as soon as the user [clicks the Print button](https://github.com/freedomofpress/securedrop-client/pull/2129/files#diff-15b630591b14cb386c8d3b74d1a37af17ea721e82303364ec99e3e5904e1753dL99-L100), and received... as soon as pyqtslots receive things. :upside_down_face:  I don't think there's much we can do about it, but I do think this is a stopgap to a better print workflow overall.
