### ISSUE TITLE
Simplify submission handling

### ISSUE THREAD

**Issue by redshiftzero** [freedomofpress/securedrop-client#231]
This is an epic tracking ongoing refactoring of our message/file/submission/reply handling, namely to:

* separate submission objects into file and message objects (both being objects sent from sources to journalists, but the message being an item that is only text that is fetched and decrypted in the background), resolving a common confusion
* store content and some additional metadata about files/messages/replies directly in the database

The associated subtickets are:

- [x] #229: separating the submissions table into files and messages
- [x] #117: track which files/messages/replies have been decrypted
- [x] #217: store message and reply text directly in the database
- [x] #230: add counter field to the database instead of having to keep parsing the beginning of the filename

**Comment by heartsucker** [comment]
Noting that we might want to add #55 first so we can be more confident that each of the subtasks here has a schema / migration that do the right thing in prod.

**Comment by heartsucker** [comment]
We may want to add #276 to this since it's a bug related to this ticket.

**Comment by redshiftzero** [comment]
closing this since these tasks are done, tackling #276 separately
