### ISSUE TITLE
Add support for community localization

### ISSUE THREAD

**Issue by eloquence** [freedomofpress/securedrop-client#239]
Given that the current SecureDrop web UI can be fully localized, having the UI of the client in English only represents a regression, which may slow down medium term adoption of the client.

We should ensure that all messages in the client can be localized via Weblate, and document the specifics of the translation process.

This is not strictly required for the beta (which will likely be only with English language newsrooms), though it would be good to lay the foundation for community translations early.

---

1. [x] #1264 
2. [x] #1265 
3. [x] #1266
4. [x] #1302
5. [x] #1317
6. [x] #1283
7. [x] #1304
8. [x] #1398
9. [x] #1438

On hold:

- [ ] #1280

**Comment by cfm** [comment]
Initial findings after familiarizing myself with the status of i18n/l10n in both `securedrop` and `securedrop-client`:

1. UI strings here are already (on spot-checking, not exhaustive inventory) wrapped in `gettext()` calls.
    - Qt has its own translation system, in which the wrapper is `QObject.tr()`.  However, the Qt ecosystem appears to be somewhere between (a) [agnostic between its native system and gettext](https://stackoverflow.com/questions/2021567/pros-and-cons-of-using-gettext-instead-of-qobject-tr-for-localization-of-pyqt4) and (b) ["just use gettext"](https://wiki.ubuntu.com/QtTranslations).  
    - #270 ([especially](https://github.com/freedomofpress/securedrop-client/pull/270#discussion_r264574640)) implies that reusing `securedrop`'s gettext-based workflow and toolchain, and the SecureDrop team's familiarity with them, is an implementation assumption of `securedrop-client`.

2. I have separately drafted a diagram of [`securedrop`'s i18n workflow](https://docs.securedrop.org/en/latest/development/i18n.html), which I'll review with @rmol with an eye to:
    1. comprehension on my part :-);
    2. any desired changes to this workflow for `securedrop-client`, such as experimenting with [PR-based](https://docs.weblate.org/en/latest/vcs.html#pushing-changes-to-github-as-pull-requests) and [continuous](https://docs.weblate.org/en/latest/admin/continuous.html) translation; and
    3. whether/how to adapt [`securedrop`'s `i18n_tool.py`](https://github.com/freedomofpress/securedrop/blob/develop/securedrop/i18n_tool.py) for `securedrop-client`.

**Comment by cfm** [comment]
In discussion with @rmol:  Let's use `securedrop-client` to test out [PR-based](https://docs.weblate.org/en/latest/vcs.html#pushing-changes-to-github-as-pull-requests) and [continuous](https://docs.weblate.org/en/latest/admin/continuous.html) translation (as a prototype for switching `securedrop` to this workflow as well).  This approach will largely obviate the need for a `i18n_tool.py` or equivalent in `securedrop-client` except for the functions of:

1. extracting source strings into `.pot`;
2. listing supported (100% translated) locales; and
    - This designation, and the process for granting/revoking it, might be worth formally reconsidering—though the stakes are lower on the Journalist Interface (and client) than on the Source Interface.
3. giving credit to contributing translators.

These operations might still have to be scripted (either separately or as Makefile targets) for manual invocation, but we should look into automating them fully in CI jobs.

**Comment by cfm** [comment]
Confirmed [this approach](https://github.com/freedomofpress/securedrop-client/issues/239#issuecomment-867852782) with @creviera.

**Comment by cfm** [comment]
With #1317 done, I've updated the [description](https://github.com/freedomofpress/securedrop-client/issues/239#issue-405934400) with the current status of this epic.  #1304 is my focus this sprint.  We can return to #1283 (which should just require retesting and a `securedrop-debian-packaging` update) next sprint.

Cc: @eloquence, @creviera

**Comment by creviera** [comment]
@cfm QA for the next release happens on the 31st of May, so I think we'll want to notify folks that we're ready for translation as soon as possible.

**Comment by cfm** [comment]
Current status, including tasks remaining to hit a May 31 formal start of QA and translation review:

1. [x] **Translatability:**  The `securedrop_client/locale/` directory is being [updated automatically](https://github.com/freedomofpress/securedrop-client/commits/main/securedrop_client/locale) as a prerequisite to merge into `main`.
2. [x] **Translation:**  Our wonderful volunteer translators are [already keeping up with translation](https://weblate.securedrop.org/projects/securedrop/securedrop-client/#history) of strings present in `main`!  Draft PR #1315 has the changes that have accumulated since this workflow was first enabled.
3. [x] **Testing:**  Localization is tested both automatically and during manual preflight testing (since #1401).
4. [x] **Documentation:**  SecureDrop's ["Translations"](https://docs.securedrop.org/en/stable/development/translations.html) page covers the Client as well as the Server workflow.  The ["Internationalization"](https://github.com/freedomofpress/securedrop-client/wiki/Internationalization) wiki page gives a technical overview.
    * For internal reference:  https://docs.google.com/document/d/1dqukHmTo45weMsPSFonagV6a6d0haXS49nF38WTTaeA/edit
6. [ ] **Limiting users to supported languages:**  I've suggested a trivial approach in <https://github.com/freedomofpress/securedrop-client/issues/1438#issuecomment-1090686136>, which I could implement in the next sprint.
7. [ ] **Announcements:**  [Drafted](https://docs.google.com/document/d/1Rh5muL-O_w-retXyWB1oLosPVhUEdfCj5yuSGl6rImE/edit#), pending team approval.

Any questions or concerns about proceeding as I've outlined here?  Anything missing?

**Comment by creviera** [comment]
Thanks for the status update. Could you describe a little more about the process of setting which languages would have their catalogs packaged (based on manually looking at translation percentage)? Like, will there be a last call for translations before a QA period so that we can figure out if we need to update the list?

**Comment by cfm** [comment]
Per <https://github.com/freedomofpress/securedrop-client/issues/1438#issuecomment-1090686136>, it would be a change in `setup.py`, basically one line +/‒ per language enabled/disabled.  Since translation is already possible and happening continuously, the pre-release timeline is up to us and Localization Lab.  Either:

1. **for more testing time:** we review and merge translations ([e.g.](https://github.com/freedomofpress/securedrop-client/pull/1315)) at the feature freeze and test them during the two-week QA window; or
2. **for more translation time:** as for the Server, we use the QA period as the official or priority translation window, merge the final translations before building the production packages, and test them during preflight testing.

Since this workflow is continuous, its tooling is stage-agnostic.  So we can choose the timeline that will suit us better, both in general and for this first time through.  What do you (and @eloquence?) think?

**Comment by cfm** [comment]
(As requested during yesterday's sprint-planning meeting, I've put finalizing this timeline on the agenda for Monday's Workstation hangout.)

**Comment by cfm** [comment]
<https://github.com/freedomofpress/securedrop-client/issues/239#issuecomment-1124447254>:

> 1. **for more testing time:** we review and merge translations ([e.g.](https://github.com/freedomofpress/securedrop-client/pull/1315)) at the feature freeze and test them during the two-week QA window; or
> 
> 2. **for more translation time:** as for the Server, we use the QA period as the official or priority translation window, merge the final translations before building the production packages, and test them during preflight testing.

Today we decided to go with option (1), so that the release manager can determine which languages to include as supported as part of preparing an RC according to the [release checklist](https://github.com/freedomofpress/securedrop-client/blob/main/.github/ISSUE_TEMPLATE/release.md).

**Comment by cfm** [comment]
With today's [announcement](https://securedrop.org/news/the-securedrop-client-is-ready-for-translation/), translation is officially open in Weblate.  All that remains here is #1497, which is ready for review apart from a test that's unexpectedly failing.

**Comment by cfm** [comment]
<https://github.com/freedomofpress/securedrop-client/issues/239#issuecomment-1178051491>:

> I'll leave this epic open until we successfully release one or more translations, which we prepared in #1531 but weren't able to include in v0.8.0.

However, since then, we _have_ released v0.8.1, which was [deliberately](https://github.com/freedomofpress/securedrop-client/issues/1558#issuecomment-1247208085) branched from v0.8.0, still without translations, rather than from `main`, where `pt_PT` (b0dc0d2973e3ae3437866b0285628320604085cf) and `zh_Hans` (42aaf10d0a53cde83c9165359a4bdb0e13286c5b) have been enabled since July 12.  I'm going to go ahead and close this epic, since:
1. no more work is planned here, which serves as the basis for freedomofpress/securedrop#6232;
2. we have preflight QA documented since #1401; and
3. we can always reopen this epic, or just file follow-up tickets, for any further work or regressions discovered for v0.9.0.
