### ISSUE TITLE
ReplyBox styling/polishing

### ISSUE THREAD

**Issue by sssoleileraaa** [freedomofpress/securedrop-client#351]
## Description

Once the following issues are addressed, make sure the reply box is using correct fonts, colors, padding, hover-over colors etc. 

## General styling and UX

- [x] ReplyBox should contain source name - #348
- [x] Indicate reply pending state - #350
- [x] Add keyboard shortcuts for sending - #606
- [ ] Add spinner for replies in progress of being sent - #359

## Offline mode styling and UX

These are on the Beta milestone but may fall off as it's a lower priority use case.

- [ ] Adjust letter-spacing - #599
- [ ] Make sign-in clickable - #600 
- [ ] Discard reply text after signing out - #601 

For styling data, see: https://app.zeplin.io/project/5c807ea562f734bd2756b243/screen/5c86f09e988ef41982386bea

**Comment by eloquence** [comment]
The remaining issue here is the reply box styling in offline mode (#349), which may fall off the beta milestone as it's a lower priority use case. I think we've completed the must-do styling for the reply box itself; there's tasks around it that remain open, most notably the addition of a spinner (#359), and the potential addition of "Retry" and "Delete" action next to individual failed replies.

I think we can safely close this tracking issue, but fine to keep it if it's helpful.

**Comment by eloquence** [comment]
Edited top-level issue to expand issue titles & add a few more related issues in case it's useful to have a tracking issue.

**Comment by zenmonkeykstop** [comment]
Closing this - #601 is still open but requires more discussion/investigation
