### ISSUE TITLE
UI Polish: Sourcelist things

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#848]
## Problem
We have a client, woo!! It works, woo!! Time to polish ye UI details...

## Solution
The below features need to be implemented  
 - [ ] [Proper scrolling UI and behavior](#474) (hide/show on mouseover) 
 - [ ] Option to de-select a source by clicking on the branding bar of the UI
    - Result would be showing no source as selected, and de-selected screen
 - [ ] [Delete "x"](#300) replacing paperclip and datestamp in Source List, when source is selected  

_All of the below, to improve Source List scanability & aesthetic appeal...
  - [ ] <strike>Linespacing not to spec</strike> « _#959 created to address_ 
  - [ ] Padding potentially not to spec or needs tweeking « ...in #867 
  - [ ] Lines separating source items need lightening per Zeplin
  - [ ] Gradient highlight on selected source  « _#958 created to address_
  - [x] <strike>Selected/unselected stars need to be replaced with correct art</strike> « #523 addressed
  - [x] <strike>Text coloration of preview likely needs to be tweeked</strike> « nope!

**Comment by eloquence** [comment]
Closing, non-critical issue specific to the current codebase/UX, which is undergoing a rewrite.
