### ISSUE TITLE
Nina's wishlist of Beta polish items

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#865]
## Problem
Nina is a pain in the ass.
Everyone else is busting their bums to debug and make-awesome this client, and there's the ux kid over there... throwing around with her gradients, her fancy typography, her "tweaked this a tad!" SVGs and whatnot.

## Solution
_Ohai! A tidy list that would be _fabulous_ if @ntoll could pull-off in time for the Beta, but if not—no worries whatsoever._ :)

- [x] Branding barre SVG update #711 
- [ ] Selected Source highlight: should be a gradient. I updated this one to perfectly match the background color in the Conversation pane. `background-image: linear-gradient(to right, #f8fefe 2%, #f3f0f9 74%, #f3f5f9 100%);`
- [x] Starring SVG updates #523 
- [x] Empty state pane layout tweeks #847 
- [ ] Tweaks to text/line colors and linespacing in Source List stuff #867
- [x] Widen da Source List per #869 

<3

**Comment by eloquence** [comment]
This is a great punchlist, thanks @ninavizz. Do we have a Zeplin screen that shows the highlight with the gradient? If not, would you mind making one? It's always good to be able to compare the final result to the design.

**Comment by ninavizz** [comment]
I can haz gradient comparison (top is my mockup, bottom is as-is in client today)...

![image](https://user-images.githubusercontent.com/8262612/75932145-91be6480-5e2b-11ea-826a-81e7df37d963.png)

Also, above gradient spec was taken from [this Zeplin](https://zpl.io/VQ8JXxP), altho I blush that you think my CSS skillz could even remotely be capable of having figured that one out. :)

**Comment by eloquence** [comment]
Thank you! As you may have noticed, right now, the hover state and the active (selected) state in the source list appear to be using an identical light grey background, which looks a bit confusing when you're hovering over the source right next to the currently selected one.

What background color would you recommend for the _hover_ state? Keep it  grey as is, change to the gradient, something else?

**Comment by ninavizz** [comment]
Ayyy... thank you for noticing that @eloquence! Ugh. 

My intended "hover" behavior, was for the big "X" and "DELETE" replacing the date and attachment icon, showing, as well as the name of the source turning `filepane-blue` (to match the selected source), along with the cursor changes.

I know everyone on our team uses Slack and Signal a lot, and I see both of them do the grey highlight. I'd never spec'd that, tho. Highlight colors for on-hover have become much less common, in recent years. 

Man, I want that delete functionality added-in... but do appreciate the scope-creep of that as a pre-Beta feature. 

Lemme noodle on this... possibly the lighter blue from the gradient, along with the Source name color change (and possibly also changing the color of the date), feel like they'd make the most sense to me short-term.

**Comment by eloquence** [comment]
Thanks! Yeah, color changes on hover may still be doable, but inline delete from within the source list is not on the table right now.

**Comment by ninavizz** [comment]
Ok... I'm kinda diggin' this. 
Will look extra sparkly/shiney once the stars are replaced with correct artwork.

![image](https://user-images.githubusercontent.com/8262612/75934713-21671180-5e32-11ea-9c4b-f5705a0c430d.png)

## On hover...
_Per [this Zeplin](https://zpl.io/VQ8JXxP)_
- [ ] Widget background color becomes `#f1fcfe`
- [ ] Source Name and Date text are colored `filepane-blue` aka `#102781`
- [ ] Paperclip SVG color changes to `filepane-blue` aka `#102781`

**Comment by ntoll** [comment]
Aha.... I'll try to get as many as these done now the blocked GUI on startup is ready for review. ;-)

**Comment by ntoll** [comment]
Hi @ninavizz, I just checked but the CSS capabilities in Qt can't do background image gradients: `background-image: linear-gradient(to right, #f8fefe 2%, #f3f0f9 74%, #f3f5f9 100%);`

It can handle solid `background-color` specifications. Happy to change if you let me know what you want.

**Comment by ntoll** [comment]
OK... all the other items on this list have been addressed and/or pushed to post-beta.

**Comment by ninavizz** [comment]
YOU are awesome, @ntoll!! QT, is... well, today it is not cute. Adding the label "Needs QT Investigation" for both the Linespacing and the Background Gradient schticks. Would be great to look into those post-release... maybe if Allie or Jen want something to do with a drink on a beach somewhere.

**Comment by eloquence** [comment]
(Closing per above.)
