### ISSUE TITLE
UI Polish: Hover States + All Starring Colors

### ISSUE THREAD

**Issue by ninavizz** [freedomofpress/securedrop-client#873]
All hover states except for in the files pane, should be spoken-to in the [Zeplin page here](https://zpl.io/V0g0MlE). 
Included in the above Zeplin page are many features, like the "x" for Delete and a fancy tooltip on the extended version of a truncated username, that are not yet implemented—and this issue presumes no expectation that they will be implemented for Beta. 

## Zeplin spec for hover + hover w/in hover
- **1:** _Ignore pre-beta_
- **2:** Unselected Star w/in Conversation Pane header
    - Same hover, pending, selected state colors, as Source List stars
  - [ ]  Fill with `#cad3ee`
  - [ ] STRETCH GOAL (eg: Nicholas, not worth crying over!) `box-shadow: 0 0 12px 3px rgba(255, 255, 255, 0.4`
   - [ ] STRETCH GOAL (eg: Nicholas, not worth crying over!) 2px white border at 50% alpha
- **3:** More icon
   - [ ] Fill with `#1FD6E3` 
- **4:** Source w/in list
   - [ ] Source name to `filepane-blue`
   - [ ] Paperclip to `filepane-blue`
   - [ ] Date to `filepane-blue`
   - [ ] Background to `#f1fcfe`
   - [ ] Star to get white dropshadow of `box-shadow: 0 0 3px 0 #ffffff;`
- **5:** _Ignore pre-beta_
- **6:** _Ignore pre-beta_
- **7:** All of the Files Pane stuff was in a separate & is now **done!**
- **8:** Star w/in Source w/in Source List
   - [ ] ON hover, background to `#80e3ff`
   - [ ] Selected, background to `#2a319d` aka `GrimaceBlue`
   - [ ] Unselected, background to `##d3d8ea` aka `unselected-star-blu`
- **9:** Awesome Airplane 
   - [ ] Background to `#80e3ff`
   - Keep same "hot" footprint; eg, don't require users to touch the exact pixels of the airplane, to enable it. Kina same for starring... it should be a nice square a few pixels outside the points of the star, to trigger the stars apart from the whole Source.
- **10:** _Ignore pre-beta_
- **11:** _Ignore pre-beta_

**Comment by ninavizz** [comment]
Note: A lot of the cyans for hover look the same... but are slightly different, depending on what the background color of the object is. Cyan is generally difficult for accessibility reasons, and as such when there's a grayish background vs white, the cyan is a little darker.

**Comment by eloquence** [comment]
(I've removed the "star pending state" in the above list, since it's not in immediate consideration.)

**Comment by eloquence** [comment]
Closing, non-critical issue specific to the current codebase/UX, which is undergoing a rewrite.
